model_type: ppo
model_path: null  # path to pretrained model
save_dir: model
run_id: testing
model_settings:
  policy: CnnPolicy
  learning_rate: 1.e-4
  tensorboard_log: tensorboards/sf2
  verbose: 1
  seed: 0
train_settings:
  total_timesteps: 2_000
  tb_log_name: PPO
  progress_bar: true